// Generated by scripts/prepare-pine-footprints.mjs from the pinned EZ-Tree Large source.
// Matches LabPines: centered X/Z, grounded Y, normalized to the three KayKit role heights.
export const pineFootprints = {
    "kaykit-conifer-a": {
        "radius": 4.800031438420059,
        "height": 10.774031221866608,
        "sourceSha256": "ba3e7e52d6fccb55d9847b02d999861597cc87d41f8548e5f59ebb21a1c85fef",
        "sourceRevision": "dcf309bd86bd521083d9c70f01f2de45fdc7c457"
    },
    "kaykit-conifer-b": {
        "radius": 3.0930534863932753,
        "height": 6.942590951919556,
        "sourceSha256": "ba3e7e52d6fccb55d9847b02d999861597cc87d41f8548e5f59ebb21a1c85fef",
        "sourceRevision": "dcf309bd86bd521083d9c70f01f2de45fdc7c457"
    },
    "kaykit-conifer-c": {
        "radius": 2.349841136020452,
        "height": 5.274394989013672,
        "sourceSha256": "ba3e7e52d6fccb55d9847b02d999861597cc87d41f8548e5f59ebb21a1c85fef",
        "sourceRevision": "dcf309bd86bd521083d9c70f01f2de45fdc7c457"
    }
} as const;
