/** Generated by scripts/update-character-registry.mjs. Do not edit by hand. */
export interface AssetMeasurement {sha256:string;triangles:number;materials:number;bytes:number;bounds:{min:number[];max:number[]};}
export const characterAssetMeasurements:Record<string,AssetMeasurement>={
    "/universal-human/UniversalHuman_LOD0.glb": {
        "sha256": "40e9e4cebdcbb796d5cbf509de52d1220635913e5a069d6b56d69afd81af6f55",
        "triangles": 8559,
        "materials": 1,
        "bytes": 3491460,
        "bounds": {
            "min": [
                -0.47737971421052117,
                6.945921820067239e-8,
                -0.16829228463259915
            ],
            "max": [
                0.47737971478540553,
                1.8000000715255737,
                0.16829239087078543
            ]
        }
    },
    "/universal-human/UniversalHuman_LOD1.glb": {
        "sha256": "5b23936dd80c9f443ebf7e144c547c80a4e1980c8d2cee5c818afe7a608829f5",
        "triangles": 4295,
        "materials": 1,
        "bytes": 1931868,
        "bounds": {
            "min": [
                -0.4773316132746601,
                6.493633869733335e-8,
                -0.16833256123124102
            ],
            "max": [
                0.4773316139348387,
                1.8000000715255737,
                0.16833266860157028
            ]
        }
    },
    "/universal-human/UniversalHuman_LOD2.glb": {
        "sha256": "5836bad2b9cc48f2dde153a55cf05395299657b343815e7a9c1833247d0eaf86",
        "triangles": 1293,
        "materials": 1,
        "bytes": 743296,
        "bounds": {
            "min": [
                -0.4773235074358296,
                7.331167653752605e-8,
                -0.16790275284424025
            ],
            "max": [
                0.47732350771409515,
                1.7999999523162842,
                0.1679028597664567
            ]
        }
    },
    "/appearance/short/Hair_short_LOD0.glb": {
        "sha256": "c2f5446acc30e2e1d2eeda0a11b874ac9ea14853c511f19476615a4e90da9cfd",
        "triangles": 1750,
        "materials": 1,
        "bytes": 137472,
        "bounds": {
            "min": [
                -0.1013844832777977,
                0.02510077692568302,
                -0.1541961431503296
            ],
            "max": [
                0.08941517770290375,
                0.12735483050346375,
                0.11093919724225998
            ]
        }
    },
    "/appearance/short/Hair_short_LOD1.glb": {
        "sha256": "f9a517851537ffae6b3e93eefc2928c58aed204db681cd3a0da66dcb8b4b7078",
        "triangles": 1750,
        "materials": 1,
        "bytes": 137472,
        "bounds": {
            "min": [
                -0.1013844832777977,
                0.02510077692568302,
                -0.1541961431503296
            ],
            "max": [
                0.08941517770290375,
                0.12735483050346375,
                0.11093919724225998
            ]
        }
    },
    "/appearance/short/Hair_short_LOD2.glb": {
        "sha256": "cbde631ced7ed2f0df2ff0f7a3bbd221432b257ed085074a8402b5367e7f845b",
        "triangles": 1750,
        "materials": 1,
        "bytes": 137472,
        "bounds": {
            "min": [
                -0.1013844832777977,
                0.02510077692568302,
                -0.1541961431503296
            ],
            "max": [
                0.08941517770290375,
                0.12735483050346375,
                0.11093919724225998
            ]
        }
    },
    "/appearance/medium/Hair_medium_LOD0.glb": {
        "sha256": "21fc719d7f2e422427e6a10af1ab4e52e23aa005bab867f4ee61b56dc7455963",
        "triangles": 867,
        "materials": 1,
        "bytes": 68748,
        "bounds": {
            "min": [
                -0.12174195796251297,
                -0.1274750977754593,
                -0.13396118581295013
            ],
            "max": [
                0.10828764736652374,
                0.12191808968782425,
                0.119914211332798
            ]
        }
    },
    "/appearance/medium/Hair_medium_LOD1.glb": {
        "sha256": "37f6f207af3545dee3b0a447ad4044d7e1c940632585863fa1d1ffb1a18d75c5",
        "triangles": 867,
        "materials": 1,
        "bytes": 68748,
        "bounds": {
            "min": [
                -0.12174195796251297,
                -0.1274750977754593,
                -0.13396118581295013
            ],
            "max": [
                0.10828764736652374,
                0.12191808968782425,
                0.119914211332798
            ]
        }
    },
    "/appearance/medium/Hair_medium_LOD2.glb": {
        "sha256": "a9bef6a69d362677e9d32a62ad76e73c98708af0adc4704487df23f01deb423a",
        "triangles": 867,
        "materials": 1,
        "bytes": 68748,
        "bounds": {
            "min": [
                -0.12174195796251297,
                -0.1274750977754593,
                -0.13396118581295013
            ],
            "max": [
                0.10828764736652374,
                0.12191808968782425,
                0.119914211332798
            ]
        }
    },
    "/appearance/long/Hair_long_LOD0.glb": {
        "sha256": "d1f3b20003da5cbe70d95138e818f3f1d42148ffc85ee09836794b821fe612d1",
        "triangles": 2800,
        "materials": 1,
        "bytes": 219524,
        "bounds": {
            "min": [
                -0.13384711742401123,
                -0.22377628087997437,
                -0.12318819016218185
            ],
            "max": [
                0.11373885720968246,
                0.12945687770843506,
                0.12188445776700974
            ]
        }
    },
    "/appearance/long/Hair_long_LOD1.glb": {
        "sha256": "d5bbf0f1b70f8d796ac111c194057af1a369d07e47b6adc78405928cffe77cc6",
        "triangles": 2800,
        "materials": 1,
        "bytes": 219524,
        "bounds": {
            "min": [
                -0.13384711742401123,
                -0.22377628087997437,
                -0.12318819016218185
            ],
            "max": [
                0.11373885720968246,
                0.12945687770843506,
                0.12188445776700974
            ]
        }
    },
    "/appearance/long/Hair_long_LOD2.glb": {
        "sha256": "bf764d2ee6a20df9c6b1f14e3df95215c229b9b5c1d2b0d6ca57baf4d38ccbe4",
        "triangles": 2800,
        "materials": 1,
        "bytes": 219524,
        "bounds": {
            "min": [
                -0.13384711742401123,
                -0.22377628087997437,
                -0.12318819016218185
            ],
            "max": [
                0.11373885720968246,
                0.12945687770843506,
                0.12188445776700974
            ]
        }
    },
    "/appearance/tied/Hair_tied_LOD0.glb": {
        "sha256": "febc9aae2de144a6e8471e852a08b2d1e82a3e47680c82d70356b241c54f4d0c",
        "triangles": 2772,
        "materials": 1,
        "bytes": 217304,
        "bounds": {
            "min": [
                -0.1531798392534256,
                -0.23574765026569366,
                -0.21953843533992767
            ],
            "max": [
                0.10607383400201797,
                0.12690767645835876,
                0.116059310734272
            ]
        }
    },
    "/appearance/tied/Hair_tied_LOD1.glb": {
        "sha256": "cc43319a2566a4bad37f37ddf2a1db96f7676ed05da332b86434c36a92ca37e5",
        "triangles": 2772,
        "materials": 1,
        "bytes": 217304,
        "bounds": {
            "min": [
                -0.1531798392534256,
                -0.23574765026569366,
                -0.21953843533992767
            ],
            "max": [
                0.10607383400201797,
                0.12690767645835876,
                0.116059310734272
            ]
        }
    },
    "/appearance/tied/Hair_tied_LOD2.glb": {
        "sha256": "d4c191df7d9d1b6fac229ed4e559c77d67b862353fc5b673fda70c61e1522364",
        "triangles": 2772,
        "materials": 1,
        "bytes": 217304,
        "bounds": {
            "min": [
                -0.1531798392534256,
                -0.23574765026569366,
                -0.21953843533992767
            ],
            "max": [
                0.10607383400201797,
                0.12690767645835876,
                0.116059310734272
            ]
        }
    },
    "/appearance/bun/Hair_bun_LOD0.glb": {
        "sha256": "6cff53fdad67fdcd3a77c2b350e613ec17775e5faec76f67bb7823edb0d66f8b",
        "triangles": 944,
        "materials": 1,
        "bytes": 67688,
        "bounds": {
            "min": [
                -0.10770214349031448,
                -0.07714761793613434,
                -0.17600642144680023
            ],
            "max": [
                0.10557599365711212,
                0.178287073969841,
                0.11018715053796768
            ]
        }
    },
    "/appearance/bun/Hair_bun_LOD1.glb": {
        "sha256": "7ec063e4fe69a089c2cb772eb468992942dc18e74cbaccd5694826a458a99bd2",
        "triangles": 944,
        "materials": 1,
        "bytes": 67688,
        "bounds": {
            "min": [
                -0.10770214349031448,
                -0.07714761793613434,
                -0.17600642144680023
            ],
            "max": [
                0.10557599365711212,
                0.178287073969841,
                0.11018715053796768
            ]
        }
    },
    "/appearance/bun/Hair_bun_LOD2.glb": {
        "sha256": "c47491e6446f70908fb85273a4fbe37389765626512212941eefb5eb79e95acd",
        "triangles": 944,
        "materials": 1,
        "bytes": 67692,
        "bounds": {
            "min": [
                -0.10770214349031448,
                -0.07714761793613434,
                -0.17600642144680023
            ],
            "max": [
                0.10557599365711212,
                0.178287073969841,
                0.11018715053796768
            ]
        }
    },
    "/appearance/braid/Hair_braid_LOD0.glb": {
        "sha256": "ce4d68d17a8c468c3ec9b149b821cc6900857ce3e80457a084c4bf021bfd3de3",
        "triangles": 3490,
        "materials": 1,
        "bytes": 273364,
        "bounds": {
            "min": [
                -0.1158444955945015,
                -0.3264067471027374,
                -0.12964394688606262
            ],
            "max": [
                0.10553868860006332,
                0.12698616087436676,
                0.15864992141723633
            ]
        }
    },
    "/appearance/braid/Hair_braid_LOD1.glb": {
        "sha256": "1fe4ee2ac30ba34929b93553c0ce9566209b233ec2702d2e5f393bd2ff35d3c9",
        "triangles": 3490,
        "materials": 1,
        "bytes": 273364,
        "bounds": {
            "min": [
                -0.1158444955945015,
                -0.3264067471027374,
                -0.12964394688606262
            ],
            "max": [
                0.10553868860006332,
                0.12698616087436676,
                0.15864992141723633
            ]
        }
    },
    "/appearance/braid/Hair_braid_LOD2.glb": {
        "sha256": "ae921bb86772a0ec6827e3961ef68a1a401c80909c942148f019f303784a9d39",
        "triangles": 3490,
        "materials": 1,
        "bytes": 273364,
        "bounds": {
            "min": [
                -0.1158444955945015,
                -0.3264067471027374,
                -0.12964394688606262
            ],
            "max": [
                0.10553868860006332,
                0.12698616087436676,
                0.15864992141723633
            ]
        }
    },
    "/appearance/beards/stubble/Beard_stubble_LOD2.glb": {
        "sha256": "08714ac62c7ae4c18130628c03641859ee81e48a71a934029fb3e809450a7da5",
        "triangles": 723,
        "materials": 1,
        "bytes": 85928,
        "bounds": {
            "min": [
                -0.10347696393728256,
                -0.12312881648540497,
                -0.07720013707876205
            ],
            "max": [
                0.10300732403993607,
                -0.0003701265377458185,
                0.11218294501304626
            ]
        }
    },
    "/appearance/beards/short/Beard_short_LOD2.glb": {
        "sha256": "226a11f9898b8228ed10dc2e4cda536a1a55ca04899412f1c07e9128cf1d7bc3",
        "triangles": 1500,
        "materials": 1,
        "bytes": 118124,
        "bounds": {
            "min": [
                -0.089634470641613,
                -0.17119187116622925,
                -0.0030734294559806585
            ],
            "max": [
                0.08369594067335129,
                -0.019787799566984177,
                0.13093513250350952
            ]
        }
    },
    "/appearance/beards/medium/Beard_medium_LOD2.glb": {
        "sha256": "9ee762b232bf9e15a764b6bf2618511c7fecb9b4060ccaf8e4383e502466c657",
        "triangles": 1498,
        "materials": 1,
        "bytes": 117964,
        "bounds": {
            "min": [
                -0.0890619233250618,
                -0.2085869461297989,
                0.0043572629801929
            ],
            "max": [
                0.08268779516220093,
                -0.02120230160653591,
                0.1505260318517685
            ]
        }
    },
    "/appearance/beards/long/Beard_long_LOD2.glb": {
        "sha256": "e6380a143e7325ed064b762fedb788a5512d202938bfc3dda7321f2073fa7c46",
        "triangles": 1498,
        "materials": 1,
        "bytes": 117964,
        "bounds": {
            "min": [
                -0.09220888465642929,
                -0.3059619963169098,
                0.004941554740071297
            ],
            "max": [
                0.09101483225822449,
                -0.02270764857530594,
                0.14105229079723358
            ]
        }
    },
    "/appearance/beards/split-braid/Beard_split-braid_LOD2.glb": {
        "sha256": "dbb68b8e3767e634fa621ced353960229640f64d1ce7d468b82987b85fa067fc",
        "triangles": 1458,
        "materials": 1,
        "bytes": 114856,
        "bounds": {
            "min": [
                -0.07353191822767258,
                -0.26719632744789124,
                -0.0051305112428963184
            ],
            "max": [
                0.07627171277999878,
                -0.029042931273579597,
                0.1489826887845993
            ]
        }
    },
    "/appearance/beards/braid/Beard_braid_LOD0.glb": {
        "sha256": "d597c85d352a06b39235cbd87ec07d44dd32ad37602b5dbf89917e9fb15d8571",
        "triangles": 1542,
        "materials": 1,
        "bytes": 121400,
        "bounds": {
            "min": [
                -0.07469377666711807,
                -0.2955496609210968,
                -0.0017717445734888315
            ],
            "max": [
                0.07549579441547394,
                -0.02308853156864643,
                0.17145514488220215
            ]
        }
    },
    "/appearance/beards/braid/Beard_braid_LOD1.glb": {
        "sha256": "b208d71746adc3c0ff580b8d10f92fda924e6e710c410293271399b8faf51502",
        "triangles": 1542,
        "materials": 1,
        "bytes": 121400,
        "bounds": {
            "min": [
                -0.07469377666711807,
                -0.2955496609210968,
                -0.0017717445734888315
            ],
            "max": [
                0.07549579441547394,
                -0.02308853156864643,
                0.17145514488220215
            ]
        }
    },
    "/appearance/beards/braid/Beard_braid_LOD2.glb": {
        "sha256": "b4d6bdbe230b3c9f7455aa2db0738a4a4802f6d9200ba287ca5d9322eb0ea9ce",
        "triangles": 1542,
        "materials": 1,
        "bytes": 121400,
        "bounds": {
            "min": [
                -0.07469377666711807,
                -0.2955496609210968,
                -0.0017717445734888315
            ],
            "max": [
                0.07549579441547394,
                -0.02308853156864643,
                0.17145514488220215
            ]
        }
    },
    "/clothing/cream-tunic/Clothing_cream-tunic_LOD2.glb": {
        "sha256": "e70aecffd92a74cb99b40e724f43109534b249d1a8746206682d2a910b95650f",
        "triangles": 3836,
        "materials": 1,
        "bytes": 470944,
        "bounds": {
            "min": [
                -0.3874010145664215,
                0.00009781800326891243,
                -0.2794952392578125
            ],
            "max": [
                0.3910473883152008,
                1.4945683479309082,
                0.1663047820329666
            ]
        }
    },
    "/clothing/long-dress/Clothing_long-dress_LOD2.glb": {
        "sha256": "ba8c08e9f38b3171aa29c4714d2df85d44341ff91294c9acb3875efe1b633112",
        "triangles": 3841,
        "materials": 1,
        "bytes": 467064,
        "bounds": {
            "min": [
                -0.37247344851493835,
                0.0014374158345162868,
                -0.3699875771999359
            ],
            "max": [
                0.39075833559036255,
                1.4884393215179443,
                0.20623818039894104
            ]
        }
    },
    "/clothing/mantle-tunic/Clothing_mantle-tunic_LOD2.glb": {
        "sha256": "bc0ae0f85734248c038e7ae4b1e156ef39dfa0fb705539ac6d4ae3222143f366",
        "triangles": 3998,
        "materials": 1,
        "bytes": 473564,
        "bounds": {
            "min": [
                -0.4359859526157379,
                0.0013079345226287842,
                -0.2780964970588684
            ],
            "max": [
                0.41303911805152893,
                1.5009708404541016,
                0.2746049165725708
            ]
        }
    },
    "/character-lab/modules/v04/equipment/sword/sword.glb": {
        "sha256": "08b65df552cd58efd9fc44ff45f562d45a9b73baeea6ab291c56ddb799ab8ff5",
        "triangles": 288,
        "materials": 1,
        "bytes": 33584,
        "bounds": {
            "min": [
                -0.12788887321949005,
                -0.14419999718666077,
                -0.060244858264923096
            ],
            "max": [
                0.1295863837003708,
                0.8858000040054321,
                0.06103011220693588
            ]
        }
    },
    "/character-lab/modules/v04/hair/bun/bun.glb": {
        "sha256": "3b1b2885c6bc6192b84b2418ecfcb163a3a2ac3ffc41860bc237ef07b383e7c1",
        "triangles": 492,
        "materials": 1,
        "bytes": 61560,
        "bounds": {
            "min": [
                -0.06838985532522202,
                -0.015874091535806656,
                -0.10278132557868958
            ],
            "max": [
                0.07037639617919922,
                0.1844988763332367,
                0.09187266230583191
            ]
        }
    },
    "/character-lab/modules/v04/hair/short/short.glb": {
        "sha256": "128826eefc475d915d227579656db86e5e2c96f02682f41e2626ebd05dbab0a3",
        "triangles": 338,
        "materials": 1,
        "bytes": 42564,
        "bounds": {
            "min": [
                -0.06443795561790466,
                -0.003989906050264835,
                -0.10519354045391083
            ],
            "max": [
                0.06469328701496124,
                0.12926490604877472,
                0.09536313265562057
            ]
        }
    }
};
