/** Generated by scripts/update-character-registry.mjs. Do not edit by hand. */
export interface AssetMeasurement {sha256:string;triangles:number;materials:number;bytes:number;bounds:{min:number[];max:number[]};}
export const characterAssetMeasurements:Record<string,AssetMeasurement>={
    "/universal-human/UniversalHuman_LOD0.glb": {
        "sha256": "40e9e4cebdcbb796d5cbf509de52d1220635913e5a069d6b56d69afd81af6f55",
        "triangles": 8559,
        "materials": 1,
        "bytes": 3491460,
        "bounds": {
            "min": [
                -0.47737971421052117,
                6.945921820067239e-8,
                -0.16829228463259915
            ],
            "max": [
                0.47737971478540553,
                1.8000000715255737,
                0.16829239087078543
            ]
        }
    },
    "/universal-human/UniversalHuman_LOD1.glb": {
        "sha256": "5b23936dd80c9f443ebf7e144c547c80a4e1980c8d2cee5c818afe7a608829f5",
        "triangles": 4295,
        "materials": 1,
        "bytes": 1931868,
        "bounds": {
            "min": [
                -0.4773316132746601,
                6.493633869733335e-8,
                -0.16833256123124102
            ],
            "max": [
                0.4773316139348387,
                1.8000000715255737,
                0.16833266860157028
            ]
        }
    },
    "/universal-human/UniversalHuman_LOD2.glb": {
        "sha256": "5836bad2b9cc48f2dde153a55cf05395299657b343815e7a9c1833247d0eaf86",
        "triangles": 1293,
        "materials": 1,
        "bytes": 743296,
        "bounds": {
            "min": [
                -0.4773235074358296,
                7.331167653752605e-8,
                -0.16790275284424025
            ],
            "max": [
                0.47732350771409515,
                1.7999999523162842,
                0.1679028597664567
            ]
        }
    },
    "/appearance/short/Hair_short_LOD0.glb": {
        "sha256": "5230753fdd064f2835c5ed69f0e35eaca0057153a71ef27a43bd02086b18375d",
        "triangles": 1383,
        "materials": 1,
        "bytes": 69984,
        "bounds": {
            "min": [
                -0.12394939363002777,
                -0.07406490296125412,
                -0.18226344883441925
            ],
            "max": [
                0.13717035949230194,
                0.19095082581043243,
                0.14198680222034454
            ]
        }
    },
    "/appearance/short/Hair_short_LOD1.glb": {
        "sha256": "104c60c0888ab65bdc41a372aa06adc57c6d21098d7ab879fa56896d3efb158a",
        "triangles": 914,
        "materials": 1,
        "bytes": 48836,
        "bounds": {
            "min": [
                -0.12411192059516907,
                -0.07406490296125412,
                -0.1825013905763626
            ],
            "max": [
                0.13718059659004211,
                0.19095082581043243,
                0.14247627556324005
            ]
        }
    },
    "/appearance/short/Hair_short_LOD2.glb": {
        "sha256": "dcfa92c73fd8454d3fce5d72a8971d417966717bb6f359c4df501bdd807a5a54",
        "triangles": 1383,
        "materials": 1,
        "bytes": 69984,
        "bounds": {
            "min": [
                -0.12394939363002777,
                -0.07406490296125412,
                -0.18226344883441925
            ],
            "max": [
                0.13717035949230194,
                0.19095082581043243,
                0.14198680222034454
            ]
        }
    },
    "/appearance/medium/Hair_medium_LOD0.glb": {
        "sha256": "cff8f9c1ca2e01a829f6e36e523a58883972b228570f9148de6a2814654db137",
        "triangles": 1256,
        "materials": 1,
        "bytes": 64260,
        "bounds": {
            "min": [
                -0.15456053614616394,
                -0.11498112231492996,
                -0.1521022766828537
            ],
            "max": [
                0.15458376705646515,
                0.18875756859779358,
                0.1529649794101715
            ]
        }
    },
    "/appearance/medium/Hair_medium_LOD1.glb": {
        "sha256": "c26bbaace906be6ad8eb85bc13990938c657d38bb4b4ba531b944de8a6c52a0e",
        "triangles": 1000,
        "materials": 1,
        "bytes": 62376,
        "bounds": {
            "min": [
                -0.1527082771062851,
                -0.11953354626893997,
                -0.1508668065071106
            ],
            "max": [
                0.15458376705646515,
                0.18875756859779358,
                0.15669582784175873
            ]
        }
    },
    "/appearance/medium/Hair_medium_LOD2.glb": {
        "sha256": "1dae74e7484a50965da43b3c2af2dbb866a84786fbaaf66471fa1592474bd54a",
        "triangles": 1256,
        "materials": 1,
        "bytes": 64260,
        "bounds": {
            "min": [
                -0.15456053614616394,
                -0.11498112231492996,
                -0.1521022766828537
            ],
            "max": [
                0.15458376705646515,
                0.18875756859779358,
                0.1529649794101715
            ]
        }
    },
    "/appearance/long/Hair_long_LOD0.glb": {
        "sha256": "eb5ad490925616b67007e0beb4bc9f74529608eabca66995eb247810e41bd9ba",
        "triangles": 1919,
        "materials": 1,
        "bytes": 114288,
        "bounds": {
            "min": [
                -0.18551501631736755,
                -0.26911717653274536,
                -0.1735357791185379
            ],
            "max": [
                0.1926560401916504,
                0.19212132692337036,
                0.19713732600212097
            ]
        }
    },
    "/appearance/long/Hair_long_LOD1.glb": {
        "sha256": "c8f055813531995ea641428693f37b62586b4218c9ef47d5aab254f0105bd1a0",
        "triangles": 1620,
        "materials": 1,
        "bytes": 101100,
        "bounds": {
            "min": [
                -0.18400917947292328,
                -0.26911717653274536,
                -0.1735357791185379
            ],
            "max": [
                0.19396889209747314,
                0.19212132692337036,
                0.1938304454088211
            ]
        }
    },
    "/appearance/long/Hair_long_LOD2.glb": {
        "sha256": "d0b7416ae395d7261a16a3181145fda9ed19f2e75f5c2a7ce6bc56f489670a8f",
        "triangles": 1919,
        "materials": 1,
        "bytes": 114288,
        "bounds": {
            "min": [
                -0.18551501631736755,
                -0.26911717653274536,
                -0.1735357791185379
            ],
            "max": [
                0.1926560401916504,
                0.19212132692337036,
                0.19713732600212097
            ]
        }
    },
    "/appearance/tied/Hair_tied_LOD0.glb": {
        "sha256": "fb05756c140289c4ccbffa2355cfc5a2715950e37cdc39e8dbf5f67d76e02b3e",
        "triangles": 2333,
        "materials": 1,
        "bytes": 138084,
        "bounds": {
            "min": [
                -0.18053333461284637,
                -0.21519601345062256,
                -0.2563309669494629
            ],
            "max": [
                0.15502512454986572,
                0.1783037632703781,
                0.1943923532962799
            ]
        }
    },
    "/appearance/tied/Hair_tied_LOD1.glb": {
        "sha256": "8d4bef31a2817d13e89a4d655425cb25dbd05b9c891ea80785de64064a34594d",
        "triangles": 2039,
        "materials": 1,
        "bytes": 127844,
        "bounds": {
            "min": [
                -0.18053333461284637,
                -0.21519601345062256,
                -0.2563309669494629
            ],
            "max": [
                0.15502512454986572,
                0.1783037632703781,
                0.1943923532962799
            ]
        }
    },
    "/appearance/tied/Hair_tied_LOD2.glb": {
        "sha256": "4d52a6eaa0e64a52e3e29c0e4d769cbf317d42076ca5d8a1df2df184510e0051",
        "triangles": 2333,
        "materials": 1,
        "bytes": 138084,
        "bounds": {
            "min": [
                -0.18053333461284637,
                -0.21519601345062256,
                -0.2563309669494629
            ],
            "max": [
                0.15502512454986572,
                0.1783037632703781,
                0.1943923532962799
            ]
        }
    },
    "/appearance/bun/Hair_bun_LOD0.glb": {
        "sha256": "e2dd078e8eab13a316b6b30a309f0054244cd480917e0f14da278bca4c5223c5",
        "triangles": 1838,
        "materials": 1,
        "bytes": 109636,
        "bounds": {
            "min": [
                -0.1167667880654335,
                -0.11253012716770172,
                -0.18549741804599762
            ],
            "max": [
                0.1292445957660675,
                0.2119535654783249,
                0.15102238953113556
            ]
        }
    },
    "/appearance/bun/Hair_bun_LOD1.glb": {
        "sha256": "5e51f73090f2664e6f6f1eb0d5251900fe14bc6dd8f4ea8e836b1b8c5e64b0d5",
        "triangles": 1588,
        "materials": 1,
        "bytes": 101804,
        "bounds": {
            "min": [
                -0.11794423311948776,
                -0.11253012716770172,
                -0.18549741804599762
            ],
            "max": [
                0.1292445957660675,
                0.2119535654783249,
                0.14983324706554413
            ]
        }
    },
    "/appearance/bun/Hair_bun_LOD2.glb": {
        "sha256": "4c004e100563f2060ec71dfe6044356a282a1064e3dd92429e63e9bd17b92372",
        "triangles": 1838,
        "materials": 1,
        "bytes": 109636,
        "bounds": {
            "min": [
                -0.1167667880654335,
                -0.11253012716770172,
                -0.18549741804599762
            ],
            "max": [
                0.1292445957660675,
                0.2119535654783249,
                0.15102238953113556
            ]
        }
    },
    "/appearance/braid/Hair_braid_LOD0.glb": {
        "sha256": "46f7bce066bfe21775d72facbdb3e0dfe0539bfe82ee21b47eaade27cf52da09",
        "triangles": 8886,
        "materials": 1,
        "bytes": 546084,
        "bounds": {
            "min": [
                -0.12428195774555206,
                -0.2500231862068176,
                -0.14922970533370972
            ],
            "max": [
                0.12932083010673523,
                0.19227240979671478,
                0.15799397230148315
            ]
        }
    },
    "/appearance/braid/Hair_braid_LOD1.glb": {
        "sha256": "5b27a4a4d084675db04b6d2398bdb0efd8e07c5f15bd90d6a7c2d91e53430cb6",
        "triangles": 8319,
        "materials": 1,
        "bytes": 506528,
        "bounds": {
            "min": [
                -0.12492977827787399,
                -0.19189970195293427,
                -0.1492711454629898
            ],
            "max": [
                0.12932083010673523,
                0.19227240979671478,
                0.13521979749202728
            ]
        }
    },
    "/appearance/braid/Hair_braid_LOD2.glb": {
        "sha256": "bd0708069f1e0b4be6c2aa1740a3e774315b1152050de88d60bc9123b29c6468",
        "triangles": 8886,
        "materials": 1,
        "bytes": 546084,
        "bounds": {
            "min": [
                -0.12428195774555206,
                -0.2500231862068176,
                -0.14922970533370972
            ],
            "max": [
                0.12932083010673523,
                0.19227240979671478,
                0.15799397230148315
            ]
        }
    },
    "/appearance/beards/stubble/Beard_stubble_LOD2.glb": {
        "sha256": "67842a4d709f490f90732836ced388642aa3e9ebf8bdd4998107131522056528",
        "triangles": 908,
        "materials": 1,
        "bytes": 51904,
        "bounds": {
            "min": [
                -0.07942614704370499,
                -0.12667138874530792,
                0.05249515175819397
            ],
            "max": [
                0.10911204665899277,
                -0.010703650303184986,
                0.16719834506511688
            ]
        }
    },
    "/appearance/beards/short/Beard_short_LOD2.glb": {
        "sha256": "f7328ebaeb77fae88af45429873ae1b4cc9017a586dc2e8dd54c8834b1e5ade6",
        "triangles": 742,
        "materials": 1,
        "bytes": 41560,
        "bounds": {
            "min": [
                -0.05191235616803169,
                -0.157439723610878,
                -0.02735225483775139
            ],
            "max": [
                0.15845175087451935,
                0.022870555520057678,
                0.1667829304933548
            ]
        }
    },
    "/appearance/beards/medium/Beard_medium_LOD2.glb": {
        "sha256": "c230b0c07329b618937e408421dc6b340cedfeb7c58668f02883a1794907557c",
        "triangles": 1070,
        "materials": 1,
        "bytes": 67500,
        "bounds": {
            "min": [
                -0.09762244671583176,
                -0.2519656717777252,
                -0.038813091814517975
            ],
            "max": [
                0.17851051688194275,
                0.005694183055311441,
                0.19815607368946075
            ]
        }
    },
    "/appearance/beards/long/Beard_long_LOD2.glb": {
        "sha256": "db0559949ed566d6a7ffcba532971660340a744588232e3d60bc878a900a4081",
        "triangles": 1189,
        "materials": 1,
        "bytes": 59796,
        "bounds": {
            "min": [
                -0.0983322486281395,
                -0.26295650005340576,
                -0.05189201608300209
            ],
            "max": [
                0.11561013013124466,
                0.03069859929382801,
                0.1313883513212204
            ]
        }
    },
    "/appearance/beards/split-braid/Beard_split-braid_LOD2.glb": {
        "sha256": "5ccce2435442e1893bf064616dbf3d22d1d606b0d55a13484ac8bc4bd59ed9cc",
        "triangles": 1240,
        "materials": 1,
        "bytes": 86092,
        "bounds": {
            "min": [
                -0.0749189481139183,
                -0.2291136234998703,
                -0.002105206251144409
            ],
            "max": [
                0.13781161606311798,
                0.009627796709537506,
                0.16866694390773773
            ]
        }
    },
    "/appearance/beards/braid/Beard_braid_LOD0.glb": {
        "sha256": "38a8872de6723a077282e95eb91c6e5459137508fc7ef26eb57eb52e6adc1dd1",
        "triangles": 2475,
        "materials": 1,
        "bytes": 253724,
        "bounds": {
            "min": [
                -0.12167009711265564,
                -0.2407001107931137,
                -0.12042970210313797
            ],
            "max": [
                0.15322846174240112,
                0.045822493731975555,
                0.17157766222953796
            ]
        }
    },
    "/appearance/beards/braid/Beard_braid_LOD1.glb": {
        "sha256": "8912f32f9fe7d2c4507530ab4932e6d8718966220cec41a16cc5ec294b0136db",
        "triangles": 1775,
        "materials": 1,
        "bytes": 182328,
        "bounds": {
            "min": [
                -0.12167009711265564,
                -0.2401488870382309,
                -0.12042970210313797
            ],
            "max": [
                0.15322846174240112,
                0.045822493731975555,
                0.17157766222953796
            ]
        }
    },
    "/appearance/beards/braid/Beard_braid_LOD2.glb": {
        "sha256": "852aba0a4ff086990f4b166a58a5b5639ccfd3a6beca4ceebd85697b9586732a",
        "triangles": 1175,
        "materials": 1,
        "bytes": 121128,
        "bounds": {
            "min": [
                -0.12167009711265564,
                -0.24036061763763428,
                -0.12042970210313797
            ],
            "max": [
                0.15322846174240112,
                0.043416209518909454,
                0.17157766222953796
            ]
        }
    }
};
