// Provenance of prepared runtime assets; regenerated by assets:human.
export const meshyHumanAssetIdentity=[
  {
    "path": "/game-assets/human/Human_LOD0.glb",
    "sha256": "8e07d3e1fcf61f4114557e36bc08f2f2fd8c634fb5b3c09b4f746e387caeadfe"
  },
  {
    "path": "/game-assets/human/Human_LOD1.glb",
    "sha256": "d5639e39b84e3a8616b28722db31be643585d10483fee74088a5477bf6df7bfd"
  },
  {
    "path": "/game-assets/human/Human_LOD2.glb",
    "sha256": "d2a05aa67337187686325f40e9dd2c4c5867517c933a09aefb857594f2faa682"
  }
] as const;

export const meshyHumanAvailableClips=[
  "Running",
  "Walking",
  "01a11653-99cc-7579-b58e-8682f15317fa",
  "Attack",
  "Fall_Dead_from_Abdominal_Injury",
  "Idle_02",
  "Idle_03",
  "Idle_11",
  "Idle_7",
  "Listening_Gesture",
  "Pull_Radish",
  "Talk_Passionately",
  "Unsteady_Walk",
  "01a11653-99cc-7579-b58e-8682f15317fa.001"
] as const;
