/** Generated by scripts/update-appearance-versions.mjs; cache identity follows published geometry. */
const versions:Record<string,string>={
    "/appearance/beards/braid/Beard_braid_LOD0.glb": "38a8872de672",
    "/appearance/beards/braid/Beard_braid_LOD1.glb": "8912f32f9fe7",
    "/appearance/beards/braid/Beard_braid_LOD2.glb": "852aba0a4ff0",
    "/appearance/beards/long/Beard_long_LOD2.glb": "db0559949ed5",
    "/appearance/beards/medium/Beard_medium_LOD2.glb": "c230b0c07329",
    "/appearance/beards/short/Beard_short_LOD2.glb": "f7328ebaeb77",
    "/appearance/beards/split-braid/Beard_split-braid_LOD2.glb": "5ccce2435442",
    "/appearance/beards/stubble/Beard_stubble_LOD2.glb": "67842a4d709f",
    "/appearance/braid/Hair_braid_LOD0.glb": "46f7bce066bf",
    "/appearance/braid/Hair_braid_LOD1.glb": "5b27a4a4d084",
    "/appearance/braid/Hair_braid_LOD2.glb": "40b3c56e6701",
    "/appearance/bun/Hair_bun_LOD0.glb": "e2dd078e8eab",
    "/appearance/bun/Hair_bun_LOD1.glb": "5e51f73090f2",
    "/appearance/bun/Hair_bun_LOD2.glb": "252884e662d3",
    "/appearance/long/Hair_long_LOD0.glb": "eb5ad4909256",
    "/appearance/long/Hair_long_LOD1.glb": "c8f055813531",
    "/appearance/long/Hair_long_LOD2.glb": "195f23397224",
    "/appearance/medium/Hair_medium_LOD0.glb": "cff8f9c1ca2e",
    "/appearance/medium/Hair_medium_LOD1.glb": "c26bbaace906",
    "/appearance/medium/Hair_medium_LOD2.glb": "3ab42c965a49",
    "/appearance/short/Hair_short_LOD0.glb": "5230753fdd06",
    "/appearance/short/Hair_short_LOD1.glb": "104c60c0888a",
    "/appearance/short/Hair_short_LOD2.glb": "dd92ecc910f9",
    "/appearance/tied/Hair_tied_LOD0.glb": "fb05756c1402",
    "/appearance/tied/Hair_tied_LOD1.glb": "8d4bef31a281",
    "/appearance/tied/Hair_tied_LOD2.glb": "ba4653b41fb6"
};
export function versionedAppearanceAsset(path:string){
    const version=versions[path];
    if(!version)throw new Error(`Missing published appearance version: ${path}`);
    return `${path}?v=${version}`;
}
