import {projectWorld} from './WorldView';
import type {SimulationState,SimulationCommand} from '../simulation/SimulationCore';
import type {Cargo,MissionType} from '../simulation/WorldExpeditions';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const date=(tick:number)=>`Winter ${Math.floor(tick/1000)} · tick ${tick%1000}`;
export class WorldControls {
 open=false;editor=false;editingId:string|null=null;name='';members=new Set<string>();regionId:string|null=null;groupId:string|null=null;mission:MissionType='Recon';priorities:Cargo[]=['Food'];
 reset(){this.open=false;this.editor=false;this.editingId=null;this.regionId=null;this.groupId=null;this.members.clear();}
 handle(button:HTMLButtonElement,state:SimulationState,command:(c:SimulationCommand)=>void):boolean {
  const d=button.dataset;
  if(d.direction){this.open=false;this.regionId=d.direction;this.groupId??=Object.keys(state.world?.groups??{})[0]??null;return true;}
  if(d.worldGroup){this.groupId=d.worldGroup;return true;}
  if(d.missionType){this.mission=d.missionType as MissionType;return true;}
  if(d.cargo){const c=d.cargo as Cargo;this.priorities=this.priorities.includes(c)?this.priorities.filter(x=>x!==c):[...this.priorities,c];return true;}
  if(d.cargoUp){const i=this.priorities.indexOf(d.cargoUp as Cargo);if(i>0)[this.priorities[i-1],this.priorities[i]]=[this.priorities[i],this.priorities[i-1]];return true;}
  if(d.action==='world-toggle'){this.open=!this.open;return true;}
  if(d.action==='world-create'){this.editor=true;this.editingId=null;this.name='';this.members.clear();return true;}
  if(d.editGroup){const g=state.world!.groups[d.editGroup];this.editor=true;this.editingId=g.id;this.name=g.name;this.members=new Set(g.memberIds.filter(id=>state.personas[id]?.deathWinter===null));return true;}
  if(d.action==='world-cancel'){this.editor=false;return true;}
  if(d.action==='world-confirm'){
   const name=(document.getElementById('expedition-name') as HTMLInputElement).value,memberIds=[...this.members];
   command(this.editingId?{type:'EditExpeditionGroup',groupId:this.editingId,name,memberIds}:{type:'CreateExpeditionGroup',name,memberIds});this.editor=false;this.open=false;this.groupId??=Object.keys(state.world?.groups??{}).at(-1)??'group-1';return true;
  }
  if(d.action==='world-dispatch'){command({type:'DispatchExpedition',groupId:this.groupId!,regionId:this.regionId!,mission:this.mission,priorities:this.mission==='Pillage'?this.priorities:[]});return true;}
  if(d.action==='world-close-region'){this.regionId=null;return true;}
  return false;
 }
 change(target:HTMLInputElement){if(target.dataset.member){if(target.checked)this.members.add(target.dataset.member);else this.members.delete(target.dataset.member);}if(target.id==='expedition-name')this.name=target.value;}
 arrows(state:SimulationState){return projectWorld(state).regions.map(r=>`<button class="region-arrow board-ui arrow-${r.direction.toLowerCase()}" data-direction="${r.id}" aria-label="Explore ${r.direction}${r.requiresShip?' coast':''}" title="${r.direction} · ${r.requiresShip?'Coast · ':''}${r.knowledge}"><strong>${{North:'↗',East:'↘',South:'↙',West:'↖'}[r.direction]}</strong><small>${r.requiresShip?'Coast':r.direction} · ${r.knowledge}</small></button>`).join('');}
 menu(state:SimulationState){
  const v=projectWorld(state),editing=this.editingId?state.world?.groups[this.editingId]:null;
  const roster=v.groups.map(g=>`<article class="group-card"><button data-world-group="${g.id}" aria-pressed="${this.groupId===g.id}"><strong>${esc(g.name)}</strong> · ${g.status}</button><p>Location: ${esc(g.location==='Home'?'Home':v.regions.find(r=>r.id===g.location)?.direction)}<br>${g.members.map(p=>`${esc(p.name)} · ${esc(p.occupation??'no occupation')} · ${p.alive?'living':'deceased'}`).join('<br>')}</p><button data-edit-group="${g.id}" ${g.status==='Away'?'disabled':''}>Edit members</button></article>`).join('');
  const choices=Object.values(state.personas).filter(p=>p.deathWinter===null).map(p=>{const eligible=v.eligible.some(e=>e.id===p.id)||editing?.memberIds.includes(p.id);return `<label class="member-choice"><input id="member-${esc(p.id)}" type="checkbox" data-member="${esc(p.id)}" ${this.members.has(p.id)?'checked':''} ${eligible?'':'disabled'}><span>${esc(p.name)}<small>${esc(p.occupation??'no occupation')} · ${p.dna.sex} · ${state.time.winter-p.birthWinter} Winters${eligible?'':' · unavailable'}</small></span></label>`;}).join('');
  const missions=v.missions.slice().reverse().map(m=>`<article class="mission-card"><strong>${m.type} · ${esc(m.groupName)}</strong><small>Destination: ${esc(v.regions.find(r=>r.id===m.regionId)?.direction)}</small><p>${m.status==='Away'?`Away · ${Math.max(0,m.returnsAt-state.time.winter*1000-state.time.tick)} ticks remaining<br>Expected return: ${date(m.returnsAt)}`:`Returned: ${date(m.returnedAt!)}<br>${esc(m.result!.summary)}${m.result!.discovery?`<br>Discovered: ${esc(m.result!.discovery.terrain)} · ${esc(m.result!.discovery.settlementName??'no settlement observed')}`:''}<br>Food ${m.result!.food} · Materials ${m.result!.materials}<br>Cattle: ${m.result!.cattleIds.map(esc).join(', ')||'none'}<br>People: ${m.result!.personaIds.map(id=>esc(state.personas[id]?.name??id)).join(', ')||'none'}<br>Casualties: ${m.result!.casualtyIds.map(id=>esc(m.memberNames[m.memberIds.indexOf(id)]??id)).join(', ')||'none'}`}</p><small>Participants: ${m.memberNames.map(esc).join(', ')}<br>Departed: ${date(m.departedAt)} · Provisions: ${m.foodCost} Food${m.priorities.length?`<br>Priorities: ${m.priorities.join(' → ')}`:''}</small></article>`).join('');
  return `<div id="world-controls" class="board-ui"><button data-action="world-toggle" aria-expanded="${this.open}" aria-controls="world-menu">World</button>${this.open?`<section id="world-menu" class="glass"><h2>Expedition groups</h2>${v.enabled?`${this.editor?`<div id="group-editor"><label>Group name<input id="expedition-name" maxlength="60" value="${esc(this.name)}"></label><div class="member-list">${choices}</div><button data-action="world-confirm">Confirm group</button><button data-action="world-cancel">Cancel</button></div>`:`<button data-action="world-create">Create recon group</button>${roster||'<p>No groups yet.</p>'}`}<h3>Mission reports</h3>${missions||'<p>No missions yet.</p>'}`:'<p>This legacy campaign has no world graph. Start a new campaign in Settings to enable expeditions.</p>'}</section>`:''}</div>`;
 }
 panel(state:SimulationState){
  const v=projectWorld(state,this.priorities),r=v.regions.find(r=>r.id===this.regionId);if(!r)return '';
  const offer=r.offers.find(o=>o.groupId===this.groupId&&o.type===this.mission);
  return `<section id="region-panel"><button data-action="world-close-region">Back to settlement</button><h2>${r.direction}${r.requiresShip?' coast':''}</h2><p>Knowledge: <strong>${r.knowledge}</strong>${r.observedAt!==null?`<br>Observed ${date(r.observedAt)}${r.stale?' · intelligence may be stale':''}`:''}</p>${r.terrain?`<p>Terrain: ${esc(r.terrain)}<br>Resource potential: ${r.resources?.map(esc).join(', ')??'none observed'}<br>Settlement: ${esc(r.settlementName??'none observed')}<br>Pillage opportunity: ${r.opportunity?'observed':'none observed'}${r.resistance?`<br>Estimated resistance: ${r.resistance}`:''}</p>`:'<p>Destination unexplored. Recon reveals terrain and possible opportunities.</p>'}${r.requiresShip?'<p class="muted">This coastal connection requires an available longship.</p>':''}<h3>Choose group</h3><div class="custom-picker">${v.groups.map(g=>`<button data-world-group="${g.id}" aria-pressed="${g.id===this.groupId}" ${g.status!=='Ready'?'disabled':''}>${esc(g.name)} · ${g.status}</button>`).join('')||'<p>Create a group through World.</p>'}</div><h3>Mission</h3><div class="custom-picker">${['Recon','Surveillance','Pillage'].map(t=>`<button data-mission-type="${t}" aria-pressed="${this.mission===t}">${t}</button>`).join('')}</div>${this.mission==='Pillage'?`<h3>Pillage priorities</h3><p class="muted">One cargo category per returning member. First available priority wins: up to ${v.carrying!.food} Food, ${v.carrying!.materials} Materials, 1 cattle or 1 person. Click to include/exclude; use ↑ to reorder.</p><div class="custom-picker">${(['Food','Materials','Cattle','People'] as Cargo[]).map(c=>`<button data-cargo="${c}" aria-pressed="${this.priorities.includes(c)}">${this.priorities.includes(c)?this.priorities.indexOf(c)+1+'. ':''}${c}</button>${this.priorities.indexOf(c)>0?`<button data-cargo-up="${c}" aria-label="Move ${c} priority up">↑</button>`:''}`).join('')}</div>`:''}${offer?.allowed?`<p>Duration: ${offer.duration} ticks<br>Provisions: ${offer.foodCost} Food (${offer.foodPerMember} per member)<br>Success chance: ${offer.successBps!/100}%<br>Death risk per member: ${offer.casualtyBps!/100}%</p>`:`<p class="warning">${esc(offer?.reason??'Select a ready group.')}</p>`}<button data-action="world-dispatch" ${offer?.allowed?'':'disabled'}>Send expedition</button><p class="muted">Members stop working and consuming Food at home while away. Surveillance is optional; a known opportunity may already allow Pillage.</p></section>`;
 }
}
